In [2]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("1806331 Dates Preprocessed2.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   business_code           50000 non-null  object 
 1   cust_number             50000 non-null  object 
 2   name_customer           50000 non-null  object 
 3   clear_date              46391 non-null  float64
 4   buisness_year           50000 non-null  int64  
 5   doc_id                  50000 non-null  int64  
 6   posting_date            50000 non-null  int64  
 7   document_create_date    50000 non-null  int64  
 8   document_create_date.1  50000 non-null  int64  
 9   due_in_date             50000 non-null  int64  
 10  invoice_currency        50000 non-null  object 
 11  document type           50000 non-null  object 
 12  posting_id              50000 non-null  int64  
 13  area_business           0 non-null      float64
 14  total_open_amount       50000 non-null

In [5]:
df=df.drop('business_code',axis=1)

In [6]:
df=df.drop('cust_number',axis=1)

In [7]:
df=df.drop('name_customer',axis=1)

In [8]:
df=df.drop('buisness_year',axis=1)

In [9]:
df=df.drop('document_create_date.1',axis=1)

In [10]:
df=df.drop('doc_id',axis=1)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   clear_date            46391 non-null  float64
 1   posting_date          50000 non-null  int64  
 2   document_create_date  50000 non-null  int64  
 3   due_in_date           50000 non-null  int64  
 4   invoice_currency      50000 non-null  object 
 5   document type         50000 non-null  object 
 6   posting_id            50000 non-null  int64  
 7   area_business         0 non-null      float64
 8   total_open_amount     50000 non-null  float64
 9   baseline_create_date  50000 non-null  int64  
 10  cust_payment_terms    50000 non-null  object 
 11  invoice_id            49994 non-null  float64
 12  isOpen                50000 non-null  int64  
dtypes: float64(4), int64(6), object(3)
memory usage: 5.0+ MB


In [12]:
df=df.drop('area_business',axis=1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   clear_date            46391 non-null  float64
 1   posting_date          50000 non-null  int64  
 2   document_create_date  50000 non-null  int64  
 3   due_in_date           50000 non-null  int64  
 4   invoice_currency      50000 non-null  object 
 5   document type         50000 non-null  object 
 6   posting_id            50000 non-null  int64  
 7   total_open_amount     50000 non-null  float64
 8   baseline_create_date  50000 non-null  int64  
 9   cust_payment_terms    50000 non-null  object 
 10  invoice_id            49994 non-null  float64
 11  isOpen                50000 non-null  int64  
dtypes: float64(3), int64(6), object(3)
memory usage: 4.6+ MB


In [14]:
df=df.drop("invoice_id",axis=1)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   clear_date            46391 non-null  float64
 1   posting_date          50000 non-null  int64  
 2   document_create_date  50000 non-null  int64  
 3   due_in_date           50000 non-null  int64  
 4   invoice_currency      50000 non-null  object 
 5   document type         50000 non-null  object 
 6   posting_id            50000 non-null  int64  
 7   total_open_amount     50000 non-null  float64
 8   baseline_create_date  50000 non-null  int64  
 9   cust_payment_terms    50000 non-null  object 
 10  isOpen                50000 non-null  int64  
dtypes: float64(2), int64(6), object(3)
memory usage: 4.2+ MB


In [16]:
df['delay']=df['clear_date']-df['due_in_date']

In [17]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   clear_date            46391 non-null  float64
 1   posting_date          50000 non-null  int64  
 2   document_create_date  50000 non-null  int64  
 3   due_in_date           50000 non-null  int64  
 4   invoice_currency      50000 non-null  object 
 5   document type         50000 non-null  object 
 6   posting_id            50000 non-null  int64  
 7   total_open_amount     50000 non-null  float64
 8   baseline_create_date  50000 non-null  int64  
 9   cust_payment_terms    50000 non-null  object 
 10  isOpen                50000 non-null  int64  
 11  delay                 46391 non-null  float64
dtypes: float64(3), int64(6), object(3)
memory usage: 4.6+ MB


In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [19]:
df['invoice_currency']=le.fit_transform(df['invoice_currency'])

In [20]:
np.unique(df['invoice_currency'])

array([0, 1])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   clear_date            46391 non-null  float64
 1   posting_date          50000 non-null  int64  
 2   document_create_date  50000 non-null  int64  
 3   due_in_date           50000 non-null  int64  
 4   invoice_currency      50000 non-null  int32  
 5   document type         50000 non-null  object 
 6   posting_id            50000 non-null  int64  
 7   total_open_amount     50000 non-null  float64
 8   baseline_create_date  50000 non-null  int64  
 9   cust_payment_terms    50000 non-null  object 
 10  isOpen                50000 non-null  int64  
 11  delay                 46391 non-null  float64
dtypes: float64(3), int32(1), int64(6), object(2)
memory usage: 4.4+ MB


In [22]:
df['document type']=le.fit_transform(df['document type'])

In [23]:
df['cust_payment_terms']=le.fit_transform(df['cust_payment_terms'])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   clear_date            46391 non-null  float64
 1   posting_date          50000 non-null  int64  
 2   document_create_date  50000 non-null  int64  
 3   due_in_date           50000 non-null  int64  
 4   invoice_currency      50000 non-null  int32  
 5   document type         50000 non-null  int32  
 6   posting_id            50000 non-null  int64  
 7   total_open_amount     50000 non-null  float64
 8   baseline_create_date  50000 non-null  int64  
 9   cust_payment_terms    50000 non-null  int32  
 10  isOpen                50000 non-null  int64  
 11  delay                 46391 non-null  float64
dtypes: float64(3), int32(3), int64(6)
memory usage: 4.0 MB


In [25]:
np.unique(df['cust_payment_terms'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75])

In [26]:
np.unique(df['document type'])

array([0, 1])

In [27]:
df['invoice_currency']=df["invoice_currency"]+1

In [28]:
df['document type']=df["document type"]+1

In [29]:
df['cust_payment_terms']=df['cust_payment_terms']+1


In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   clear_date            46391 non-null  float64
 1   posting_date          50000 non-null  int64  
 2   document_create_date  50000 non-null  int64  
 3   due_in_date           50000 non-null  int64  
 4   invoice_currency      50000 non-null  int32  
 5   document type         50000 non-null  int32  
 6   posting_id            50000 non-null  int64  
 7   total_open_amount     50000 non-null  float64
 8   baseline_create_date  50000 non-null  int64  
 9   cust_payment_terms    50000 non-null  int32  
 10  isOpen                50000 non-null  int64  
 11  delay                 46391 non-null  float64
dtypes: float64(3), int32(3), int64(6)
memory usage: 4.0 MB


In [31]:
df=df.drop('clear_date',axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   posting_date          50000 non-null  int64  
 1   document_create_date  50000 non-null  int64  
 2   due_in_date           50000 non-null  int64  
 3   invoice_currency      50000 non-null  int32  
 4   document type         50000 non-null  int32  
 5   posting_id            50000 non-null  int64  
 6   total_open_amount     50000 non-null  float64
 7   baseline_create_date  50000 non-null  int64  
 8   cust_payment_terms    50000 non-null  int32  
 9   isOpen                50000 non-null  int64  
 10  delay                 46391 non-null  float64
dtypes: float64(2), int32(3), int64(6)
memory usage: 3.6 MB


In [32]:
df=df.drop('posting_id',axis=1)

In [33]:
train_set=df[df['delay'].notnull()]

In [34]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46391 entries, 0 to 46390
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   posting_date          46391 non-null  int64  
 1   document_create_date  46391 non-null  int64  
 2   due_in_date           46391 non-null  int64  
 3   invoice_currency      46391 non-null  int32  
 4   document type         46391 non-null  int32  
 5   total_open_amount     46391 non-null  float64
 6   baseline_create_date  46391 non-null  int64  
 7   cust_payment_terms    46391 non-null  int32  
 8   isOpen                46391 non-null  int64  
 9   delay                 46391 non-null  float64
dtypes: float64(2), int32(3), int64(5)
memory usage: 3.4 MB


In [35]:
test_set=df[df['delay'].isnull()]

In [36]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3609 entries, 46391 to 49999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   posting_date          3609 non-null   int64  
 1   document_create_date  3609 non-null   int64  
 2   due_in_date           3609 non-null   int64  
 3   invoice_currency      3609 non-null   int32  
 4   document type         3609 non-null   int32  
 5   total_open_amount     3609 non-null   float64
 6   baseline_create_date  3609 non-null   int64  
 7   cust_payment_terms    3609 non-null   int32  
 8   isOpen                3609 non-null   int64  
 9   delay                 0 non-null      float64
dtypes: float64(2), int32(3), int64(5)
memory usage: 267.9 KB


In [37]:
train_set_X=train_set.drop('delay',axis=1)
train_set_Y=train_set['delay']
test_set_X=test_set.drop('delay',axis=1)
test_set_Y=test_set['delay']

In [38]:
train_set_X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46391 entries, 0 to 46390
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   posting_date          46391 non-null  int64  
 1   document_create_date  46391 non-null  int64  
 2   due_in_date           46391 non-null  int64  
 3   invoice_currency      46391 non-null  int32  
 4   document type         46391 non-null  int32  
 5   total_open_amount     46391 non-null  float64
 6   baseline_create_date  46391 non-null  int64  
 7   cust_payment_terms    46391 non-null  int32  
 8   isOpen                46391 non-null  int64  
dtypes: float64(1), int32(3), int64(5)
memory usage: 3.0 MB


In [39]:
train_set_Y

0         3.0
1         0.0
2        19.0
3        14.0
4        -1.0
         ... 
46386    -9.0
46387     2.0
46388    -4.0
46389    -4.0
46390     2.0
Name: delay, Length: 46391, dtype: float64

In [40]:
test_set_X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3609 entries, 46391 to 49999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   posting_date          3609 non-null   int64  
 1   document_create_date  3609 non-null   int64  
 2   due_in_date           3609 non-null   int64  
 3   invoice_currency      3609 non-null   int32  
 4   document type         3609 non-null   int32  
 5   total_open_amount     3609 non-null   float64
 6   baseline_create_date  3609 non-null   int64  
 7   cust_payment_terms    3609 non-null   int32  
 8   isOpen                3609 non-null   int64  
dtypes: float64(1), int32(3), int64(5)
memory usage: 239.7 KB


In [41]:
test_set_Y

46391   NaN
46392   NaN
46393   NaN
46394   NaN
46395   NaN
         ..
49995   NaN
49996   NaN
49997   NaN
49998   NaN
49999   NaN
Name: delay, Length: 3609, dtype: float64

In [42]:
np.random.seed(20)
X_train,X_test,Y_train,Y_test=train_test_split(train_set_X,train_set_Y,test_size=0.2)

In [43]:
from sklearn.ensemble import RandomForestRegressor


In [44]:
model=RandomForestRegressor(n_estimators=300,max_depth=8)

In [45]:
model.fit(X_train,Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=8, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=300, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [46]:
model.score(X_test,Y_test)

0.3743994006400274

In [47]:
test_set_Y=model.predict(test_set_X)
test_set_Y

array([ -1.57898357,   1.15332857,   1.34081791, ...,   1.15944838,
         0.17161935, -27.10023312])

In [48]:
clear_date_df=test_set_X['due_in_date']+test_set_Y

In [49]:
clear_date_df

46391    43923.421016
46392    43939.153329
46393    43919.340818
46394    43949.925444
46395    43939.982293
             ...     
49995    43938.961484
49996    43957.948604
49997    43932.159448
49998    43901.171619
49999    43944.899767
Name: due_in_date, Length: 3609, dtype: float64

In [50]:
final=np.ceil(clear_date_df)

In [51]:
final=final.astype(int)

In [52]:
from datetime import datetime

In [53]:
ans=[]

In [54]:
for i in final:
    i=datetime.fromordinal(datetime(1900,1,1).toordinal()+i-2)
    i=i.timetuple()
    ans.append(i)

In [55]:
ans

[time.struct_time(tm_year=2020, tm_mon=4, tm_mday=3, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=4, tm_yday=94, tm_isdst=-1),
 time.struct_time(tm_year=2020, tm_mon=4, tm_mday=19, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=110, tm_isdst=-1),
 time.struct_time(tm_year=2020, tm_mon=3, tm_mday=30, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=90, tm_isdst=-1),
 time.struct_time(tm_year=2020, tm_mon=4, tm_mday=29, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=120, tm_isdst=-1),
 time.struct_time(tm_year=2020, tm_mon=4, tm_mday=19, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=110, tm_isdst=-1),
 time.struct_time(tm_year=2020, tm_mon=4, tm_mday=12, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=103, tm_isdst=-1),
 time.struct_time(tm_year=2020, tm_mon=4, tm_mday=21, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=112, tm_isdst=-1),
 time.struct_time(tm_year=2020, tm_mon=4, tm_mday=28, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=119, tm_isdst=-1),
 time.struct_time(t